// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATstH05gzI5vJQEHJFoPirfxxrhHgiESU',
    appId: '1:746912992424:web:161e9b2fbdf12dd193869d',
    messagingSenderId: '746912992424',
    projectId: 'internship-task-2332',
    authDomain: 'internship-task-2332.firebaseapp.com',
    storageBucket: 'internship-task-2332.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC14eJBVIn1QTm74QNCFcdo6_RUOxt9RD8',
    appId: '1:746912992424:android:5dba9377aa3b0bd193869d',
    messagingSenderId: '746912992424',
    projectId: 'internship-task-2332',
    storageBucket: 'internship-task-2332.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbqR5BJdZUVKFY4DoPUc61z20rBdnb5Yk',
    appId: '1:746912992424:ios:d1f78a8ea3d92d3593869d',
    messagingSenderId: '746912992424',
    projectId: 'internship-task-2332',
    storageBucket: 'internship-task-2332.appspot.com',
    iosClientId: '746912992424-nju9s7s3cair7eiu8iuumlqsdjgvdj9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbqR5BJdZUVKFY4DoPUc61z20rBdnb5Yk',
    appId: '1:746912992424:ios:d1f78a8ea3d92d3593869d',
    messagingSenderId: '746912992424',
    projectId: 'internship-task-2332',
    storageBucket: 'internship-task-2332.appspot.com',
    iosClientId: '746912992424-nju9s7s3cair7eiu8iuumlqsdjgvdj9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipTask',
  );
}
